### PR TITLE
added MFA code auto-generation

### PR DESCRIPTION
**Pull request by quinnaissance**
this is what I did in lecture today teehee

### CODE REVIEW

**Comment by zach1502** [comment]
Nice work so far.
Could you make it so that the user has the option of manually inputting or automatically inputting mfa?
Thanks

**Comment by quinnaissance** [comment]
I made it so that's implicit in asking for the secret:
`self.data['mfa_secret'] = input("Paste your 16-char MFA secret (hit Enter if you don't have this)")`
i.e. user hits Enter -> MFA is not automated. Do you just want an extra (more descriptive) yes/no line for ease of use?

**Comment by zach1502** [comment]
I mean give the option for a user with MFA to manually input it instead of it doing it automatically.

**Comment by quinnaissance** [comment]
It already does that; that's what I was saying above: if you don't enter an MFA secret — where it says "hit Enter if you don't have this" — it asks you to put in a code manually (the way you had it originally). Or maybe I'm misreading?

What I was saying at the end of my first reply is that I could add an extra prompt asking "do you want to automate MFA" and then ask for the secret, instead of only asking for the secret. The reason I didn't initially do this is because I just figured if someone has their MFA secret on hand I'd assume they're competent enough to know what providing it implies.

**Comment by zach1502** [comment]
oh that's my bad. I didn't see that part. PR Approved.

**Pull request merged**
